# Generated by Django 5.0.2 on 2024-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_tag', to='services.tag'),
        ),
    ]
