# Generated by Django 5.0.2 on 2024-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='message1',
            field=models.TextField(null=True),
        ),
    ]
