# Generated by Django 5.0.2 on 2024-02-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments_message1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='message1',
        ),
    ]
