# Generated by Django 5.0.2 on 2024-02-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_category_remove_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='content',
            name='quote',
            field=models.BooleanField(default=False),
        ),
    ]
