# Generated by Django 5.0.2 on 2024-02-28 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_episodelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EpisodeLike',
            new_name='BlogLike',
        ),
        migrations.RenameField(
            model_name='bloglike',
            old_name='episode',
            new_name='blog',
        ),
    ]
