# Generated by Django 5.0.2 on 2024-02-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_episodelike_bloglike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.comments'),
        ),
    ]
