# Generated by Django 5.0.2 on 2024-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='basemodel_ptr',
        ),
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=121, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
