# Generated by Django 5.0.2 on 2024-02-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=12),
            preserve_default=False,
        ),
    ]
