# Generated by Django 5.0.2 on 2024-02-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
