# Generated by Django 5.0.2 on 2024-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_remove_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
