# Generated by Django 5.0.2 on 2024-02-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_number1',
        ),
    ]
